[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
yield_vault = "CeHNmAJaE8K2yBEo8RRoh5whacchiq1gpqzJVuL8Df97"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000
shutdown_wait = 1000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "8Yrt9b811JVDn7Ejng7ZPSGV2HT7vg9Rwc7wPmkdCgFy"
filename = "./dumps/accounts/8Yrt9b811JVDn7Ejng7ZPSGV2HT7vg9Rwc7wPmkdCgFy.json"

[[test.validator.account]]
address = "sergAK7rTYLao2v7whZytuXrwyw5snxvA7sLoaoMKLk"
filename = "./dumps/accounts/sergAK7rTYLao2v7whZytuXrwyw5snxvA7sLoaoMKLk.json"

[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"

[[test.validator.clone]]
address = "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"

[[test.validator.clone]]
address = "7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF"

[[test.validator.clone]]
address = "D6q6wuQSrifJKZYpR1M8R4YawnLDtDsMmWM1NbBmgJ59"

[[test.validator.clone]]
address = "B8V6WVjPxW1UGwVDfxH2d2r8SyT4cqn7dQRK6XneVa7D"

[[test.validator.clone]]
address = "Bgq7trRgVMeq33yt235zM2onQ4bRDBsY5EWiTetF4qw6"

[[test.validator.clone]]
address = "9DrvZvyWh1HuAoZxvYWMvkf2XCzryCpGgHqrMjyDWpmo"

[[test.validator.clone]]
address = "2s37akK2eyBbp8DZgCm7RtsaEz8eJP3Nxd4urLHQv7yB"

[[test.validator.clone]]
address = "4qp6Fx6tnZkY5Wropq9wUYgtFxXKwE6viZxFHg3rdAG8"

[[test.validator.clone]]
address = "7jaiZR5Sk8hdYN9MxTpczTcwbWpb5WEoxSANuUwveuat"

[[test.validator.clone]]
address = "MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA"

[[test.validator.clone]]
address = "3uxNepDbmkDNq6JhRja5Z8QwbTrfmkKP8AKZV5chYDGG"
